services:
  kafka-ui:
    ports:
      - "8089:8080" # Development only
  todomanagement.api:
    ports:
      - "32701:8080"   # Development only: CAP dashboard, debugging, etc.
  socketmanagement.api:
    ports:
      - "32702:8080"   # Development only: CAP dashboard, debugging, etc.